language: java
sudo: required
dist: bionic

jdk:
  - openjdk11

addons:
  apt:
    packages:
      - ant
  sonarcloud:
    organization: "dita-ot-plugins"
    token:
      secure: "nQWwmgDYMUBCxtt+YfHns/3lv4ThygmyTasqwOsmwCTXLvjhlswyU1frJLUpAQhf+ldZwVXIek4v2EHgsUXYLtd0TYrxQz/KmmYaBSeZwZiOy2eKCE+rMArcKEsPgMnfPRzG1KVA5HoZsLSdiEOIOxgJx32JBe+zlzjeKqDuHKC6IqJh3c5gVdPO6uLYmGGUb/lYbuhz8ugIoBEhhk47ssZBzsaaVWhhJdZjcUFOmkJAuKmC9gKI3R994EiMZBTOo6we00XpywXhwcgv+Ir9MYiV4NKc+dP5eoOwun0ZM6b4YlImFXs2pU/Udz8QmvK1Swa6kDU1nnMz4nWloolfmIyT8OslskVw5H1irA6J7+513GrIWsJTOEAjE85NcfPAp1+yZ4qNyfJHTGgdeAYK1ePJH+HGpX2WDqECwKMOAJCRfI72fkVSvBJlUHfgH4TVABA5UpgwmtpT7jBVWvlnduczwdpvnSnxa/ebgaU7KWF/IBiXlvnjT3bvFUZ8MB1JRWuydDpbgY03PCoaXORFInPk7/wl3DLjX3cWaJ+NiJKit9DalWaqfsYpmZgl5B7TiHQTR792Jt63lYknWJQxU2Ky3G8THAUW/vD7XMQ++qhJk5zm64cMozrey1K/eq/kD6w7lT4ZaLUR9+rs73G/tyd3tfgW0hS/Vd6UqRUpf60="

script:
  - true

after_success:
  - sonar-scanner 
